[package]
name = "scrooge"
version = "0.1.0"
authors = ["Rafael Caricio <rafael@caricio.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1.21"
config = "0.9"
human-size = "0.4"
log = "0.4"
pretty_env_logger = "0.3"
lazy_static = "1.3"
unicase = "2.3"
